### ISSUE TITLE
Domain provisoning failures showing to other users

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/aps2-addon#18] opened 2017-03-20 04:51 UTC
### Version information
APS 2.0-15

### Steps to replicate
Unable to replicate

 1. A user logged in to OA
 1. The user tried to toggle protection for one of the email users
 1. The user received several errors related to domains that failed to provision that are unrelated to his account

### Actual result
Errors messages showing domain provisioning errors unrelated to the logged in user.

### Expected result
No errors to show which are not related to the logged in user.

### Other notes
Ticket: #320682

**Comment by for93t** [comment] 2017-03-20 05:46
The application stores it's status messages in PHP sessions which cannot be shared between 2 different users "by design". In order to investigate the issue the following additional info is required:

- Is is the same browser used for both sessions or different browsers? And ...
- if the latter - PHP session identifiers for both auth sessions. Can be seen in browser cookies.

Thanks!

**Comment by for93t** [comment] 2017-03-20 08:36
I'm investigating the issue on our sandbox.

**Comment by dreasvandonselaar** [comment] 2017-03-23 11:43
FWIW the user is unable to reproduce this or provide more details.

**Comment by alexkiro** [comment] 2017-04-27 05:37
This could not be replicated, closing it for now.

**Closed by alexkiro** 2017-04-27 05:37 UTC
Labels: bug, invalid, priority-normal
