### ISSUE TITLE
APS protecting all mailboxes despite only one selected

### ISSUE THREAD

**Issue by VicSpam01** [SpamExperts/aps2-addon#19] opened 2017-03-20 13:27 UTC
### Version information
APS 2.0-15
Operations Automation 7.0

### Steps to replicate

 1. In the APS package go to the Email Users tab
 1. Apply a filter on a domain, to only list mailboxes related to that domain
 1. Select the resulting mailboxes and click "Protect"

### Actual result

The protect operation runs for all mailboxes related to the subscription, instead of the selected ones.

### Expected result

You'd expect the Protect action to only trigger for the selected email users.

### Other notes
Support: #526066

![screenshot](https://cloud.githubusercontent.com/assets/4503663/24556832/f8f4196a-1635-11e7-8300-96271939425f.PNG)

**Comment by dreasvandonselaar** [comment] 2017-04-12 07:26
Apparently it's not possible to select individual mailboxes in the Odin UI, you can only use the "select all" on top. Hence it may be an Odin bug instead, where that option selects all results instead of the filtered results. Odin did not want to confirm/deny this. Lowering to low priority.

**Comment by dreasvandonselaar** [comment] 2017-04-16 06:58
Odin posted an explanation of the issue and solution: http://kb.odin.com/en/130653

**Comment by catalinDonici** [comment] 2017-04-25 12:31
FWIW, I was unable to replicate this issue on one of our sandboxes.

**Comment by catalinDonici** [comment] 2017-04-25 12:38
Anyway, it does work after the latest changes as well.

**Comment by catalinDonici** [comment] 2017-04-26 04:41
I wasn't able to replicate the issue because I wasn't using the correct `Operations Automation`. I tried again, this time with success as I was able to see the issue on one of the sandboxes. 

However, after applying the fix the issue is still there. @for93t, can you please have a look.

**Comment by LaurentiuTeodorescu** [comment] 2021-07-27 11:18
This was fixed in https://github.com/SpamExperts/aps2-addon/pull/51

**Closed by LaurentiuTeodorescu** 2021-07-27 11:18 UTC
Labels: bug, priority-low
