### ISSUE TITLE
APS2 wrongly protecting domains based on account instead of subscription level

### ISSUE THREAD

**Issue by dreasvandonselaar** [SpamExperts/aps2-addon#25] opened 2017-04-18 10:29 UTC
### Version information

APS 2.0-15

### Steps to replicate

When provisioning SpamExperts together with e.g. Hosted Exchange plan, the autoprotection apparently is enabling protection on wrong domains which do not have mailhosting configured in the subscription.

For example:
example1.ext has email hosting enabled for subscription 12345 Hosted Exchange
example2.ext has email hosting enabled for subscription 22222 webhosting

example2.ext is automatically protected by SpamExperts, however SpamExperts is only included in the Hosted Exchange plan. 

### Actual result

All domains which are in the account are autoprotected.

### Expected result

Only domains that have the SpamExperts subscription should be protected.

### Other notes

Odin reviewed this case. 
```
1. Whenever one try to access the panel in APS, this screen is built by APS itself which for your information retrieve all details needed for the screen via RQL to OA APS resources.

2. As for the reported SpamExpert APS, it uses below RQL to retrieve the domain listing which then displayed in the screen (this can be seen clearly in the Firebug plugin in Firefox):

----------------------------------------------------------------------------------------------------

https://***/aps/2/resources/f4aa9eaf-7106-4f68-8ae1-***/domains?limit(0,10)

----------------------------------------------------------------------------------------------------

3. As you can see above, the ID 'f4aa9eaf-7106-4f68-8ae1-***' actually refers to the account 1006*** and thus, '/domains' actually refers to all domains under this account.

4. Due to no filtration design within SpamExpert APS itself, this RQL then retrieve those domains as it is and this can be seen processed within /var/log/pa/core.log

5. You may also verify this by running curl command below which you will see that it retrieves all of the domains under this account rather than domains within subscription:

-----------------------------------------------------------------------------------------------------------------------------------------------------------

curl -k -E /usr/local/pem/APS/certificates/poa.pem -X GET "https://127.0.0.1:6308/aps/2/resources/f4aa9eaf-7106-4f68-8ae1-***/domains?limit(0,10)"

-----------------------------------------------------------------------------------------------------------------------------------------------------------
```

ST: #437018 (includes log details)

**Comment by for93t** [comment] 2017-04-19 16:59
The information provided by Odin is known and it's an intended behavior - in order to show domains which are not protected yet all of them should be retrieved. This is why the application retrieves domains via an RQL query to account level resources. The domains which are protected under other subscription are not shown - there are `.../aps/2/resources?implementing(http://aps.spamexperts.com/app/domain/1.0),not(linkedWith(a1ba70f2-****-483c-b93c-****))` requests which are responsible for the filtering. So that Odin's statement - "Due to no filtration design ..." - is not correct.

@dreasvandonselaar, for me it is not clear what does "Only domains that have the SpamExperts subscription" means. Could you please advice on the exact criteria that makes a distinction between domains with and without SpamExperts subscription? Thank you!

**Comment by dreasvandonselaar** [comment] 2017-04-21 08:41
@for93t if I understand it correctly, the account has multiple subscriptions. Some of the subscriptions are linked to a service template with SpamExperts enabled. However not all domains/subscriptions have the SpamExperts resources included. The customer indicates those domains are also listed, even though there is no SpamExperts resource attached to it. And that we'd wrongly "protect" those domains. I can provide more details via DM when required (or in the ticket).

**Comment by for93t** [comment] 2017-06-16 13:22
After an email conversation with Odin support I have better understanding on how it can be fixed. Now I'm working on making this work in a testing environment. Hopefully the fix will be ready soon.

**Comment by lorentina** [comment] 2017-06-23 08:58
@for93t I verified both the old version and the fixed version.
My conclusion is that the issue is no longer present in the fixed version.
However, please notice that the Login button (to access Spampanel), for protected domains, no longer works.

**Comment by for93t** [comment] 2017-07-11 10:22
@lorentina, I'm unable to reproduce the problem you have mentioned. Can you please provide your steps or (ideally) prepare a working environment there the issue can be seen?

**Comment by catalinDonici** [comment] 2017-07-17 15:34
I wasn't able to replicate the issue.

**Comment by for93t** [comment] 2017-07-26 09:01
The fix has been published.

**Closed by for93t** 2017-07-26 09:01 UTC
Labels: bug, priority-normal, testing
